name: 'Update Repository Topics'
description: 'Use the integration manifest to assign default topics to repositories'
inputs:
  input-file: 
    description: 'Integration Manifest with integration_type definition'
    required: false
    default: './integration-manifest.json'
  repo-token: 
    description: 'Integration Manifest with integration_type definition'
    required: true
  type-token-map: 
    description: 'Integration Manifest with integration_type definition'
    required: false
    default: '[["orchestrator", "keyfactor-universal-orchestrator"],["windows-orchestrator", "keyfactor-orchestrator"],["ca-gateway", "keyfactor-cagateway"], ["pam", "keyfactor-pam"], ["api-client", "keyfactor-api-client"]]'

outputs:
  dbg-out: 
    description: 'Debug output'
runs:
  using: 'node16'
  main: 'dist/index.js'